services:
  erpnext:
    image: erpnext-mariadb
    build: .
    container_name: erpnext-mariadb
    restart: always
    ports:
      - "8080:8000"
    environment:
      MARIADB_HOST: 192.168.202.138
      MARIADB_PORT: 3306
      MARIADB_ERPNEXT_ROOT: erpnext_admin
      MARIADB_PASSWORD: Security
      FRAPPE_ADMIN_PASSWORD: "Security"
